export const APP_BASE_URL = 'https://api.themoviedb.org';

export const APP_QUERY_MAP = {
  // Screens
  PROFILE: 'PROFILE',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  MOVIE_DETAILS: 'MOVIE_DETAILS',
  VIEW_ALL_MOVIES: 'VIEW_ALL_MOVIES',
  PROFILE_VIEW_ALL_MOVIES: 'PROFILE_VIEW_ALL_MOVIES',

  // Widgets
  TRENDING_MOVIES: 'TRENDING_MOVIES',
  POPULAR_MOVIES: 'POPULAR_MOVIES',
  SEARCHED_RESULTS: 'SEARCHED_RESULTS',
  NOW_PLAYING_MOVIES: 'NOW_PLAYING_MOVIES',
  TOP_RATED_MOVIES: 'TOP_RATED_MOVIES',
  UPCOMING_MOVIES: 'UPCOMING_MOVIES',
  RECOMMENDED_MOVIES: 'RECOMMENDED_MOVIES',
  SIMILAR_MOVIES: 'SIMILAR_MOVIES',
  FAVORITE_MOVIES: 'FAVORITE_MOVIES',
  EXPLORE_MOVIES: 'EXPLORE_MOVIES',
  WATCHLIST_MOVIES: 'WATCHLIST_MOVIES',
  MOVIE_REVIEWS: 'MOVIE_REVIEWS',
  SELF_RATED_MOVIES: 'SELF_RATED_MOVIES',
  MOVIES_TRAILER: 'MOVIES_TRAILER',

  // Miscellaneous
  MOVIE_GENRES: 'MOVIE_GENRES',
};
