export const kTABS = {
  MAIN_TAB: 'MAIN_TAB', // * Root Tab
  HOME_TAB: 'HOME_TAB',
  WATCHLIST_TAB: 'WATCHLIST_TAB',
};

export const kSTACKS = {
  MAIN_STACK: 'MAIN_STACK', // * Root Stack
  LAUNCH_STACK: 'LAUNCH_STACK',
  MAIN_TAB: 'MAIN_TAB', // * Root Tab
  HOME_STACK: 'HOME_STACK',
  WATCHLIST_STACK: 'WATCHLIST_STACK',
};

export const kROUTES = {
  // landing Screens:-
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  WATCHLIST_SCREEN: 'WATCHLIST_SCREEN',
};
