export const APP_TABS_MAP = {
  MAIN_TAB: 'MAIN_TAB', // * Root Tab
  HOME_TAB: 'HOME_TAB',
  SEARCH_TAB: 'SEARCH_TAB',
  PROFILE_TAB: 'PROFILE_TAB',
};

export const APP_STACKS_MAP = {
  MAIN_STACK: 'MAIN_STACK', // * Root Stack
  LAUNCH_STACK: 'LAUNCH_STACK',
  AUTH_STACK: 'AUTH_STACK',
  MAIN_TAB: 'MAIN_TAB', // * Root Tab
  HOME_STACK: 'HOME_STACK',
  SEARCH_STACK: 'SEARCH_STACK',
  PROFILE_STACK: 'PROFILE_STACK',
};

export const APP_PAGES_MAP = {
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  SIGN_IN_SCREEN: 'SIGN_IN_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  SEARCH_SCREEN: 'SEARCH_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  WATCHLIST_SCREEN: 'WATCHLIST_SCREEN',
  FAVORITE_SCREEN: 'FAVORITE_SCREEN',
  MOVIE_VIEW_ALL_SCREEN: 'MOVIE_VIEW_ALL_SCREEN',
  MOVIE_DETAILS_SCREEN: 'MOVIE_DETAILS_SCREEN',
  MOVIE_ABOUT_SCREEN: 'MOVIE_ABOUT_SCREEN',
  MOVIE_REVIEWS_SCREEN: 'MOVIE_REVIEWS_SCREEN',
  MOVIE_SIMILAR_SCREEN: 'MOVIE_SIMILAR_SCREEN',
};

export const APP_WIDGETS_MAP = {
  HEADER_TITLE: 'HEADER_TITLE',
  NOW_PLAYING: 'NOW_PLAYING',
  UPCOMING_MOVIES: 'UPCOMING_MOVIES',
  TOP_RATED_MOVIES: 'TOP_RATED_MOVIES',
  POPULAR_MOVIES: 'POPULAR_MOVIES',
  RECOMMENDED_MOVIES: 'RECOMMENDED_MOVIES',
  QUOTATION: 'QUOTATION',
  SIMILAR_MOVIES: 'SIMILAR_MOVIES',
  SEARCHED_RESULTS: 'SEARCHED_RESULTS',
  MOVIE_POSTER: 'MOVIE_POSTER',
  FAVORITE_MOVIES: 'FAVORITE_MOVIES',
  WATCHLIST_MOVIES: 'WATCHLIST_MOVIES',
};
